### ISSUE TITLE
Loading fonts bug (1.17.1)

### ISSUE THREAD

**Issue by sheeperino** [RedLime/SpeedRunIGT#10]
Moving a font in the fonts folder and reloading resourcing/restarting the game, will make the game reload resources endlessly.
[latest.log](https://github.com/RedLime/SpeedRunIGT/files/7775770/latest.log)

### Workaround:
Remove any font from the fonts folder

**Comment by RedLime** [comment]
I think you sent wrong log file, check it please.

**Comment by sheeperino** [comment]
That's the latest.log

**Comment by RedLime** [comment]
Fixed in 2.15.1
