### ISSUE TITLE
"is_hardcore" & "is_coop" in the records file is always false

### ISSUE THREAD

**Issue by iinterp** [RedLime/SpeedRunIGT#130]
**Describe the bug**
"is_hardcore" is incorrectly false in hardcore worlds
"is_coop" is incorrectly false in co-op worlds

**To Reproduce**
1. Create a hardcore world
2. When the record file for the world is created "is_hardcore" will be false

---

1. Create a world
2. Open to LAN
4. Connect to the LAN world with another account
5. When the record file for the world is created "is_coop" will be false

**Versions info:**
 - MC Version: 1.16.1
 - SpeedRunIGT Version: 14.1+1.16.1
 - Fabric Loader Version: 0.14.21
 - No other mods (also tested with the usual speedrun mods, still doesn't work)

**Additional context**
I'm not sure if there are other steps for a world to be successfully marked as co-op

**Comment by tildejustin** [comment]
this seems related, run_type is random_seed in 1.12 when generating a world with a set seed

**Comment by tildejustin** [comment]
re the issue description: the values are only set after timer completion

**Comment by RedLime** [comment]
Will be fixed in 14.2
