### ISSUE TITLE
Option to right-align the timer and/or always show hours

### ISSUE THREAD

**Issue by theothertored** [RedLime/SpeedRunIGT#131]
When the IGT (RTA too I assume) timer switches into hours, it adds an additional digit at the start which causes the entire thing to shift. I'd like my timer's right edge to stay aligned with the right edge of the hotbar:

![image](https://github.com/RedLime/SpeedRunIGT/assets/17922244/7671ff16-b635-43c6-8844-9caf79a9ce51)

But when hours come up this stops being aligned:

![image](https://github.com/RedLime/SpeedRunIGT/assets/17922244/1152da39-4b57-46a2-a878-f344fcf03260)

"Always show hours" could be an option like the sub-second digit count, 0 by default and then 1, 2, 3 or maybe even 4 hour digits for people that would like to time their IGT on a long-running world.

And a question, I'm playing on 1.18.2, if this gets added, will it be available on earlier versions of minecraft?

**Comment by RedLime** [comment]
Implemented in 14.2.
