### ISSUE TITLE
don't work "Mine a chunk RTA" in Superflat World

### ISSUE THREAD

**Issue by zp3n** [RedLime/SpeedRunIGT#134]
It doesn't work "Mine a chunk RTA" in Superflat World.
When I mine a block, the timer will stop soon.

Uploading adebf266-9ff2-4037-a309-5ecf0f698af9.mp4…

**Comment by zp3n** [comment]
https://github.com/RedLime/SpeedRunIGT/assets/137734383/f0c8aec6-556f-4739-baaa-a491f1cc7173

**Comment by RedLime** [comment]
It's fixed in 14.1, not released yet. but there's prerelease, so you can use that.

**Comment by zp3n** [comment]
thanks for answered!
