### ISSUE TITLE
Could you make a port to 20w14infinite of this mod?

### ISSUE THREAD

**Issue by Patr1ck28** [RedLime/SpeedRunIGT#2]
The title says it all really, I mainly run 20w14infinite, which is the 2020 april fools snapshot, and would like you to start supporting that version as well as the others, hopefully that's not too hard to do

**Comment by RedLime** [comment]
oh, well.
but currently, there are too many version brunches to hard to manage.
The version will be updated with the 2.12 version update, but no later updates will be provided.

**Comment by RedLime** [comment]
Ported in 2.12.
close issue! thanks for your contribution!
