### ISSUE TITLE
Fabric Loader @ 0.12.2 or above

### ISSUE THREAD

**Issue by SirSquilliamFancyson** [RedLime/SpeedRunIGT#20]
When trying to launch using your mod, I've been getting an error spat back at me that I need fabric loader @ 0.12.2 or above. That would be fine, except I'm at a loss at how to install 0.12.2, as I can only find up to 0.12.12 for fabric loader. 

edit: sorry about the bug label, i dont know how to change that

**Comment by RedLime** [comment]
yeah, you can use 0.12.12 fabric loader.
