### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by DoubtfulGamer** [RedLime/SpeedRunIGT#25]
![Minecraft Speedrun Timer Mod Crash](https://user-images.githubusercontent.com/96815471/151666291-522e595f-b3d5-49f2-a8f0-fbb740c4f796.png)
The game crashes when I run the game

The game runs fine if I remove this mod from the "mods" folder

Other mods that I use:
Auto Reset 1.2.0
Fast Reset 1.4.0
Lazy DFU 0.1.2
Lithium 0.6.3
Sodium 0.1.1
Starlight 1.0.0 RC2
Voyager 1.0.0

**Comment by RedLime** [comment]
can you send logs pleaee?

**Comment by DoubtfulGamer** [comment]
Here it is
[2022-01-25-2.log](https://github.com/RedLime/SpeedRunIGT/files/7963995/2022-01-25-2.log)

**Comment by RedLime** [comment]
update your fabric loader.

**Comment by DoubtfulGamer** [comment]
Oh, that's a simple fix. Thanks a lot for your help!
