### ISSUE TITLE
Can Only Stop/Restart Timer Once on Multiplayer Server

### ISSUE THREAD

**Issue by loef** [RedLime/SpeedRunIGT#31]
VERSION INFORMATION -
     Minecraft Version: 1.18.1
     Fabric Loader: 0.13.3
     SpeedrunIGT: 2.19

I know this isn't exactly the purpose of the mod, but I'm using the mod to track my total playtime on a multiplayer server using the custom% category. I can start the timer once, using the restart hotkey allowing it to show up, but it will no longer show up after the first time restarting it. I'm not sure if I'm missing some way to fix this, but this is the only ingame way to easily track total playtime in a world in the HUD.

**Comment by RedLime** [comment]
wait please for 7.2 release ;)
