### ISSUE TITLE
IGT won't pause when change dimension.

### ISSUE THREAD

**Issue by hilberthp** [RedLime/SpeedRunIGT#32]
I think the problem still persist in the newest version of speedrunIGT (7.2.2) as you can see in [this clip](https://streamable.com/iwcuiw) when I try to play some ssg.
SpeedrunIGT version: [SpeedRunIGT-7.2.2+1.17.1](https://github.com/RedLime/SpeedRunIGT/releases/download/7.2/SpeedRunIGT-7.2.2+1.17.1.jar)

**Comment by RedLime** [comment]
will fixed in 7.2.3

**Comment by hilberthp** [comment]
cool, thanks redlime!

**Comment by RedLime** [comment]
please check is solved in 7.2.3 :)

**Comment by hilberthp** [comment]
can confirm it works now. Thanks for the fix!
