### ISSUE TITLE
clicking on font tab crash

### ISSUE THREAD

**Issue by acewhite1010** [RedLime/SpeedRunIGT#34]
![image](https://user-images.githubusercontent.com/93954880/157637116-7907cea6-283e-4532-b11c-e54169fe4571.png)

details: on java 16, using fabric loader 0.12.12, using version 8.0 on mc1.16.1
wtf: launched game, clicked into options > timer options > timer display options, went to click on the "font" tab and then it crashed

crash log: [hs_err_pid19772.log](https://github.com/RedLime/SpeedRunIGT/files/8222261/hs_err_pid19772.log)

**Comment by acewhite1010** [comment]
oh and btw, have deleted %appdata%\.minecraft\speedrunigt folder completely before installing speedrunigt 8.0, and then relaunched it, currently there's only options.txt inside the folder

**Comment by RedLime** [comment]
check this pinned issue #13
