### ISSUE TITLE
Mod doesn't work for me

### ISSUE THREAD

**Issue by AdamIsaksson** [RedLime/SpeedRunIGT#35]
I have the .jar files of both the mod and the fabric loader in the mods folder, but the timer and the button in the options screen doesn't show up when I launch the game. What could the reason be for this?

**Comment by Crsuh2er0** [comment]
oh u shouldnt put fabric loader in the mods folder
instead plz install it(just double click it)

**Comment by RedLime** [comment]
😏close this issue
