### ISSUE TITLE
issue about dying? not sure

### ISSUE THREAD

**Issue by acewhite1010** [RedLime/SpeedRunIGT#37]
**timer version: latest 8.0; fabric loader 0.12.12, minecraft 1.16.1**
so i was simulating some raids for new strat and then i came across with this
[options.txt](https://github.com/RedLime/SpeedRunIGT/files/8237414/options.txt)
when i **die**, and 1. **click respawn: game crashes** (aka saves world and closes game) 2. **click back to menu screen and then press esc: game crashes**. (only these two cases cuz these are AFAIK) 
first i assumed that it's a vanilla issue,  and then this happened frequently and never happened before i changed to the newer version of the mod; removed the timer mod and it doesnt happen; checked logs and timer mod is mentioned.
[crash-2022-03-12_17.31.00-client.txt](https://github.com/RedLime/SpeedRunIGT/files/8237421/crash-2022-03-12_17.31.00-client.txt) report i get when clicking back to menu screen and then press esc
also lost a crash report for "clicking the respawn button" scenario, lmk if you need one

**Comment by RedLime** [comment]
definitely bug I unexpected. will be fix next relese.

**Comment by RedLime** [comment]
Fixed in 8.2
