### ISSUE TITLE
Speedrun record in the "records" folder seems to be doubled on death in portal

### ISSUE THREAD

**Issue by 774marin** [RedLime/SpeedRunIGT#38]
**Describe the bug**
I was playing RSG, using the [new reset tracker by Specnr](https://github.com/Specnr/ResetTracker), and after completing a run I noticed it was doubled in Raw Data ([sheet](https://docs.google.com/spreadsheets/d/1Jr415P1bgyTzKnP0ut3s79VrL6N78shhKa91W57vhX4/edit?usp=sharing) for reference).
The important thing is that I (intentionally) died in the fountain before the dragon animation ended.
When I checked the _speedrunigt/records_ folder, I noticed there were two files for the same world.

**To Reproduce**
1. Play an rsg run
2. Die in the fountain just before the dragon death animation finishes
3. Respawn in the overworld
4. Check the _records_ folder. There's two files for the world.

**Expected behavior**
Only one file is created and updated.

**Screenshots or logs**
Files from the run as described: [records.zip](https://github.com/RedLime/SpeedRunIGT/files/8257901/records.zip)

**Versions info :**
 - MC Version: 1.16.1
 - SpeedRunIGT Version: 8.2.1
 - Fabric Loader Version: 0.12.19

**Comment by RedLime** [comment]
Fixed in 8.2.2, Now timer files are separated by UUIDs so that no duplicate files are write by the same world.
