### ISSUE TITLE
After running /time set 0, a player rejoining the server will cause the timer to jump forward

### ISSUE THREAD

**Issue by DuncanRuns** [RedLime/SpeedRunIGT#45]
**Describe the bug**
After running `/time set 0`, any player rejoining will set the timer as if the command was never ran.

**To Reproduce**
1. Open a server with SpeedrunIGT
2. Join the server
3. After waiting a bit, run `/time set 0` to restart the timer
4. Rejoin the world or have any other player join
5. The timer should jump forwards as if the command was never ran

**Expected behavior**
Only the first player joining should start the timer, and then the timer should restart on `/time set 0`. There should be no other cases that the timer restarts or changes.

**Screenshots or logs**
[Video showing the issue](https://www.youtube.com/watch?v=lSDlNZev--U)

**Versions info :**
 - MC Version: 1.15.2
 - SpeedRunIGT Version: 10.0
 - Fabric Loader Version: 0.13.3

**Additional context**
This issue is a major setback for any 5-9 or 10+ category, as rejoins are frequent, whether they intentional or not.

**Comment by RedLime** [comment]
fixed in 10.1 :)
