### ISSUE TITLE
1.8.9 first imput issue

### ISSUE THREAD

**Issue by gearity** [RedLime/SpeedRunIGT#48]
1.8.9 ssgp "start on first imput" isn't working, it still starts on world load, any idea?

**Comment by RedLime** [comment]
![image](https://user-images.githubusercontent.com/25276450/167382885-fda8e00f-3ea9-4ac0-8f9f-241145ee3e0a.png)
did you enabled this option? if so disable it

**Comment by gearity** [comment]
never had it on

**Comment by RedLime** [comment]
could you send video with change timer decimals to 3?

**Comment by RedLime** [comment]
coul
