### ISSUE TITLE
SpeedrunIGT working in the background

### ISSUE THREAD

**Issue by Abhirup0** [RedLime/SpeedRunIGT#49]
I redownloaded all my speedrun practice maps yesterday around 9 pm and was playing on them. SpeedrunIGT was working fine. At night i closed minecraft and switched off my laptop and went to sleep. But today around 11am i opened minecraft to practice in those maps and the RTA in all of them is 14+ hours. How?

**Comment by Abhirup0** [comment]
also i am using the latest version of the mod

**Comment by RedLime** [comment]
it is normally. yeah lol 
technically it is correct that the RTA is 14+ hours.
you can adjust RTA timer size to 0% or ignore that

**Comment by Abhirup0** [comment]
ooh i thought thats not was was supposed to happen. Thanks have a nice day
