### ISSUE TITLE
'More' Button in Timer Category Screen doesn't work

### ISSUE THREAD

**Issue by contariaa** [RedLime/SpeedRunIGT#54]
**Describe the bug**
When clicking on the 'More' Button next to the Timer Category, nothing happens and an error is printed into the log.

**To Reproduce**
1. Use SRIGT 10.17 in Minecraft version 1.16.1
2. Go to 'Timer Category' Screen
3. Click on any 'More' button next to a timer category

**Expected behavior**
It should have taken me to the categories site on speedrun.com

**Screenshots or logs**
[latest.log](https://github.com/RedLime/SpeedRunIGT/files/9332722/latest.log)

**Versions info :**
 - MC Version: 1.16.1
 - SpeedRunIGT Version: 10.17
 - Fabric Loader Version: 0.13.3

**Comment by contariaa** [comment]
It stopped working in 10.15

**Comment by contariaa** [comment]
https://github.com/RedLime/SpeedRunIGT/commit/ab878cf22dc9e04646914bf03dad7db06f1567f0#diff-7d9622e297b09797bfda5bed193b5174ca796e504fb0dae003deef03e9268580

this seems to be the commit that broke it

**Comment by RedLime** [comment]
Merged pull request
