### ISSUE TITLE
Timer keeps running during loads

### ISSUE THREAD

**Issue by kingdinocharge** [RedLime/SpeedRunIGT#6]
When going through dimension loads IGT keeps running

**Comment by kingdinocharge** [comment]
only for 1.14 that i know of

**Comment by RedLime** [comment]
can you send video about this issue? I playtested on 1.14.4, it works fine.

**Comment by kingdinocharge** [comment]
https://imgur.com/qjz5lz1

**Comment by RedLime** [comment]
what are you using SRIGT version?

**Comment by RedLime** [comment]
Fixed issues in 1.14.2!
