### ISSUE TITLE
timer gets hidden by achievement in 1.8.9

### ISSUE THREAD

**Issue by contariaa** [RedLime/SpeedRunIGT#70]
**Describe the bug**
When getting an achievement in 1.8.9, the advancement popup covers the timer. this probably affects other versions around it aswell

**To Reproduce**
1. open Minecraft 1.8.9 with SpeedrunIGT 11.4
2. put your timer in the top right corner
3. go into a world and open your inventory, the achievement that will pop up is going to hide the timer

**Expected behavior**
in 1.16.1 the timer stays above the advancement, so i assume thats what is supposed to happen

**Screenshots or logs**
![screenshot](https://user-images.githubusercontent.com/98704937/193888348-fd7cb2b6-0815-47e9-8a49-46bb20593b63.png)

**Versions info :**
 - MC Version: 1.8.9
 - SpeedRunIGT Version: 11.4
 - Fabric Loader Version: 0.14.9

**Comment by RedLime** [comment]
Fixed this issue in 12.0
