### ISSUE TITLE
how to change the records' path

### ISSUE THREAD

**Issue by pipesmart** [RedLime/SpeedRunIGT#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or logs**

**Versions info :**
 - MC Version: [e.g. 1.16.1]
 - SpeedRunIGT Version: [e.g. 2.15.2]
 - Fabric Loader Version: [e.g. 0.12.12] 

**Additional context**

**Comment by RedLime** [comment]
for consistent across all devices, the record path cannot be changed
