### ISSUE TITLE
Timer's IGT randomly stopped in the middle of the run while RTA didn't

### ISSUE THREAD

**Issue by maskersss** [RedLime/SpeedRunIGT#76]
speedrunigt version: 11.4
mc version: 1.16.1
fabic loader version: 0.14.9

idk how to reproduce it, it just happened randomly, never happened before
after i rejoined the world, igt kept counting from when it stopped (from 4:21.xxx)

files from the world folder in saves:
igt_freeze.log: https://pastebin.com/fsFkekGd
record.json: https://pastebin.com/KsTtw7yn

the srigt extension that was used during the run: https://pastebin.com/Zq0Q2kZW

a clip of it happening: https://www.youtube.com/watch?v=tigyLqc-Fa4

the srigt folder in world files: [speedrunigt.zip](https://github.com/RedLime/SpeedRunIGT/files/9844647/speedrunigt.zip)

**Comment by RedLime** [comment]
Fixed in 12.4
