### ISSUE TITLE
Putting a Disc in a Jukebox Breaks the Timer

### ISSUE THREAD

**Issue by DCMii** [RedLime/SpeedRunIGT#82]
**Describe the bug**
For whatever reason using a disc on any Timer Category (only tested Custom and AA, but assuming that all have the same problem) resets the timer, setting both RTA and IGT to the same thing. It also for some reason ignores what decimal value you set it to, and always puts it at 3.

**To Reproduce**
1. Load up any world with the timer enabled
2. Insert any disc in a juke box
3. Now the timer's at 0:00.000 and will start counting upwards
**Expected behavior**
For the timer to not be affected and continue as normal.

**Screenshots or logs**
![2022-11-09_20 31 28](https://user-images.githubusercontent.com/85907252/200994222-e082397b-bcc7-4b19-9844-cd8bb83943b9.png)
![2022-11-09_20 31 29](https://user-images.githubusercontent.com/85907252/200994260-8faa709d-c53e-4b86-9000-c57de72cabde.png)

**Versions info**
 - MC Version: 1.19.2
 - SpeedRunIGT Version: 13.0.2
 - Fabric Loader Version: 0.14.9

**Additional context**
The timer can be fixed by relogging in and out of the world, however the time period at which the timer was broken will not be accounted for.

**Comment by RedLime** [comment]
Fixed in 13.1
