### ISSUE TITLE
1.19.2 launch crash

### ISSUE THREAD

**Issue by hype00** [RedLime/SpeedRunIGT#86]
**Disclaimer**
I've never done a github issue so sorry if I'm doing it wrongly

**Describe the bug**
The 13.1 version of this mod (which is the only version I tested) in Minecraft 1.19.2 causes the game to not be able to start up, at least with MultiMC but that shouldn't be the issue I guess.

**To Reproduce**
1. Install and open MultiMC 5 Version 0.7.0 (the newest version)
2. Add a 1.19.2 instance
3. Select that instance, click "Edit Instance", click "Install Fabric", click "OK"
4. With this instance still selected, click "Minecraft Folder" and drag the jar file of this mod in the mods folder\
5. Double-click the instance to launch

**Expected behavior**
This should just launch Minecraft but instead it crashes.

**Screenshots or logs**
This opens the "Minecraft Log" window in MultiMC. I got the logs attached below.

**Versions info :**
 - MC Version: [1.19.2]
 - SpeedRunIGT Version: [13.1]
 - Fabric Loader Version: [0.14.17] 

[my logs.txt](https://github.com/RedLime/SpeedRunIGT/files/10950710/my.logs.txt)

**Comment by RedLime** [comment]
1.19.2 is not support version
