### ISSUE TITLE
How the hell I restart the timer? 

### ISSUE THREAD

**Issue by kuronekony4n** [RedLime/SpeedRunIGT#87]
How the hell I restart the timer? 
I already on custom catergory, enabled the settings for old world and limitless reset, but nothing happened when i press the keybind.
And your discord link is dead.
![Screenshot_607](https://user-images.githubusercontent.com/38156932/232965519-e41e5bfc-2d47-464a-93d3-eaf74adbcb85.png)

**Comment by RedLime** [comment]
https://discord.gg/7G2tfP7Xpe could you join discord server?

**Comment by kuronekony4n** [comment]
no
![Screenshot_608](https://user-images.githubusercontent.com/38156932/233540504-20f23dbf-8a39-49bd-8bb4-fa629162b5cf.png)
