### ISSUE TITLE
[Enhancement] Move records folder from home directory

### ISSUE THREAD

**Issue by jfsen** [RedLime/SpeedRunIGT#89]
**Describe the bug**
On my Archlinux install, using SpeedRunIGT in MultiMC, the mod creates a `speedrunigt` folder directly in my home directory.
The `speedrunigt` folder in the directory of the Minecraft instance remains unused.

**Expected behavior**
I would prefer, if the records were stored in the directory of the Minecraft instance, or alternatively, if the folder was renamed to `.speedrunigt` to make it hidden by default.

Config, cache and other application folders are not usually stored as unhidden folders in `~`

**Screenshots or logs**
![Screenshot from 2023-07-23 14-36-15](https://github.com/RedLime/SpeedRunIGT/assets/47889681/2929e224-e9bd-4dec-8b73-2197a4252475)

**Versions info :**
 - MC Version: 1.16.1 in MultiMC 0.7.0-3772
 - SpeedRunIGT Version: 13.6+1.16.1
 - Fabric Loader Version: 0.14.21

**Comment by RedLime** [comment]
Fixed from #93

**Comment by DuncanRuns** [comment]
By creating a `.hidden` file in the home directory with the simple contents `speedrunigt`, it should hide the folder. This may not happen by default for some machines, so see the full answer I found here: <https://superuser.com/a/816004>
