### ISSUE TITLE
1.14 Crash 

### ISSUE THREAD

**Issue by Eimerplayz127** [RedLime/SpeedRunIGT#9]
For some reason my game basically just crashes when i use the mod v2.14 Idk why, can I get help?

**Comment by RedLime** [comment]
please send with logs

**Comment by kingdinocharge** [comment]
if you're using optifine & optifabric dont, 1.14 optifabric is buggy

**Comment by RedLime** [comment]
solved this compatibility issue in 2.15.2. thanks :D
